version: "2"

volumes:
  db: {}

services:

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./app/build/:/var/www/app/
      - ./site/public/:/var/www/site/
      - ./borzoi/nginx/:/opt/borzoi/nginx/
    links:
      - node
    environment:
      - NGINX_CONF
      - NGINX_CERT_NAME
    ports:
      - "${NGINX_HTTPS_PORT}:443"
    entrypoint: /opt/borzoi/nginx/entrypoint.sh
    command: ["nginx", "-g", "daemon off;"]

  db:
    restart: always
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306

  node: &node
    image: node:8
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./borzoi/node/:/opt/borzoi/node/
      - ./app:/home/node/app
    expose:
      - "8081"
    entrypoint: /opt/borzoi/node/entrypoint.sh
    command: "npm run start"
  
  webpack:
    << : *node
    expose: []
    command: "npm run build"
  
  hugo:
    image: jojomi/hugo:0.36
    volumes:
      - ./site/:/src
      - ./site/public/:/output
    command: "hugo"